### ISSUE TITLE
TODOs after CSE1110 2022

### ISSUE THREAD

**Issue by mauricioaniche** [cse1110/andy#118]
List of future features for Andy: 

- if Andy doesn't find tests, show the exception (simulate it by writing an invalid method source method; add a tip saying that this is probably because the method source is throwing an exception, if they are using MethodSource in the test)
- give more tips when pitest fails (usually use of static in the test class or shared state)
- update to new pitest 1.9.2
- analytics module
- extra parameter in the checks and meta tests, that if that fails, the entire grade of the exercise becomes 0 (or subtracted by something)
- if error message is about lots of compilation errors and "did not find symbols", give a tip saying that for them to look at the first occurrence of the problem, and check whether it's valid java there"
- can we assert it's a real pbt? maybe if we find a way to count the number of times the method under test is called
- if coverage == 0, make the whole grade 0 (sometimes some code checks pass, giving students points)
- have the Jacoco annotation to not count coverage default in Andy, so that we don't need to add it in every library we need it.

**Comment by mauricioaniche** [comment]
By Frank: 

As for the coverage == 0 thing: we do have this in Andy:

```
        if (totalBranches == 0) {
            return 1f;   // full points assigned
        }
```
as well as this:

```
(total > 0 && weight==0 ? " (0 gives full points)":"")
```

The message in latter makes explicit what happens. But this is not shown in the case we had today:

```
--- Assessment
Branch coverage: 0/0 (overall weight=0.10)
Mutation coverage: 0/3 (overall weight=0.20)
Code checks: 4/4 (overall weight=0.10)
Meta tests: 0/7 (overall weight=0.60)

Final grade: 20/100
```

(I expected the grade to be 10/100 but it is 20 because the branch coverage gave full points.)

Maybe the condition should be total == 0 instead, so it is always explicit that full points are awarded. Or maybe we should just quit the entire grading calculation and show an error along the lines of "Some assessment criteria have a total number of achievable points of 0. Contact the course staff to get this fixed."

**Comment by martinmladenov** [comment]
I converted each of those points into separate (more detailed) issues to keep track of them more easily.
