### ISSUE TITLE
Code check that subtracts points

### ISSUE THREAD

**Issue by mauricioaniche** [cse1110/andy#168]
Sometimes we want code checks that don't give points if the student get them right, but subtract points from the students that got them wrong.

**Comment by martinmladenov** [comment]
Perhaps we can modify required code checks to support this instead of failing the entire submission. That way, if we want a certain code check to fail the submission, we can simply make it subtract 100 points.

**Comment by mauricioaniche** [comment]
Good idea!

**Comment by martinmladenov** [comment]
Splitting the meta test part of this issue into a separate issue: #209
