### ISSUE TITLE
Accept Mockito's doReturn(...).when(...) construct 

### ISSUE THREAD

**Issue by mauricioaniche** [cse1110/andy#197]
Andy currently only understands `when(...).thenReturn(...)`, but `doReturn(...).when(...)` is also a valid construct, although less conventional.

As we are here, we should also support `doNothing(...).when(...)` :)

**Comment by adonev42** [comment]
I'm gonna do it

**Comment by mauricioaniche** [comment]
Great, this ticket is now yours, @adonev42! Thanks for your contribution to Andy!

**Comment by mauricioaniche** [comment]
#216 closes this issue.
