### ISSUE TITLE
Add assertThat method in the list of recommended imports 

### ISSUE THREAD

**Issue by martinmladenov** [cse1110/andy#80]

**Comment by mauricioaniche** [comment]
Hmm, I don't remember what this one was about. Maybe it was was about
recommending "assertThat" if the test has no assertions or something? Do we
do it?
--
*Maurício Aniche*
Tech Academy Lead at Adyen
Assistant Professor in Software Engineering at TU Delft
Author of Effective Software Testing: A Developer's Guide
<https://www.effective-software-testing.com>
https://www.mauricioaniche.com

**Comment by martinmladenov** [comment]
@mauricioaniche 
> Hmm, I don't remember what this one was about. Maybe it was was about recommending "assertThat" if the test has no assertions or something? Do we do it?

I think it refers to the list of imports in the solution templates of exercises. We already do that in all (new) exercises.

We don't do anything special if a student's test has no assertions - we simply run tests as usual. We only have a code check that can detect that and fail if there are no assertions.

**Comment by mauricioaniche** [comment]
Then, let's close this one!
--
*Maurício Aniche*
Tech Academy Lead at Adyen
Assistant Professor in Software Engineering at TU Delft
Author of Effective Software Testing: A Developer's Guide
<https://www.effective-software-testing.com>
https://www.mauricioaniche.com
